### ISSUE TITLE
Stay Up to Date with NPM Releases

### ISSUE THREAD

**Issue by thefringeninja** [giggio/npm-nuget#9]
There have been about 60 releases of https://github.com/npm/npm since this repo was updated. With npm/npm@1569304 out this is more important than ever, since it should fix most of the long path problems that we have using NPM on windows.

**Comment by giggio** [comment]
@thefringeninja  I am not taking care of this anymore because VS 2015 and ASP.NET 5 are almost out and deal better with Node and NPM. But I will take Pull Requests to fix it.

**Comment by thefringeninja** [comment]
Hey, thanks for the quick reply! I would love to send a PR, however I don't see exactly how a specific version of NPM is selected. In fact, it looks like whatever the latest NPM is just gets installed. So maybe we don't really have to do anything here...

**Comment by thefringeninja** [comment]
Or not? I am completely confused now. So tools/node_modules is .gitignored, but those contents are nonetheless included in the nupkg? I am not sure what I would be able to do with a pull request.

**Comment by giggio** [comment]
The only thing that would have to be updated is the nuspec file. I ignored the node_modules folder because it does not make much sense to add all npm files here. Latest stable version of npm is 2.12.0. We could simply test it and make sure it works. The thing is I am not having time to work on it, and the latest published version is 1.35.15, so there might be breaking changes. If you can update the nuspec file and test it, send a PR and I will verify and publish it.

**Comment by lijunle** [comment]
Reading [the breaking changes from 1.x to 2.x](https://github.com/npm/npm/blob/master/CHANGELOG.md#v200-2014-09-12), I don't think that is a big deal.

Besides, I think the individual NPM packages need to care about the NPM version, but this nuget package does not need to care.

I am going to pump up version to [`2.12.1`](https://github.com/npm/npm/blob/master/CHANGELOG.md#v2121-2015-06-25). 

---

Because I don't find how the version number is consumed to generate the `tools/node_module` folder. I will just modify the number and **not** test offline.

It there is a script, please check in.

**Comment by lijunle** [comment]
Hi, @giggio 

One cons of the current version (1.3.15.10) is that, it does not support `color`, `spin` and `unicode` config arguments. So, the npm command output in VS output windows will mess up.

IMO, it is a worth to upgrade the version to 2.x.

Could you please take a look?

**Comment by giggio** [comment]
I am pushing now 2.13.1 to Nuget .org. I tested and it worked fine. The dependency on Node has been updated to 0.12.7.
